README.md, circle.yml
=> Add circleci

core/ui/fields/field_dropdown.js
Reverts code-dot-org/blockly#15
Wrong branch.
=> Revert "Optionally call changehandler in setTitleValue"

.circleci/config.yml, circle.yml
Mostly just used the auto-generated config and removed the parts we didn't need.
=> Update blockly to use Circle 2.0

core/connections/connection.js, core/initialization/inject.js, core/ui/block_svg/block_svg.js, tests/playground.html, tests/playground_requires.js
=> Triangular block tabs for sprite-typed connections

core/ui/block_space/flyout.js
Fix for PR https://github.com/code-dot-org/blockly/pull/91.
=> Bug fix: only count user-visible blocks

tests/block_space_test.js, tests/blocks_test.js, tests/hidden_blocks_test.js, tests/test_requires_and_utils.js, tests/unused_blocks_test.js
I merged https://github.com/code-dot-org/blockly/pull/90 into the wrong branch :crying_cat_face:
=> Clean up the dom after every test

core/connections/connection.js, core/ui/block_svg/block_svg.js, tests/playground.html, tests/playground_requires.js
Modeled after PR https://github.com/code-dot-org/blockly/pull/99.
LTR:
RTL:
=> Rounded connections

core/ui/block.js, core/ui/block_space/block_space.js, core/ui/block_space/trashcan.js
=> Put a red slash over the trash can when dragging undeletable blocks

core/ui/block_space/block_space.js, core/ui/block_space/block_space_editor.js
=> Cross-tab copy / paste

blocks/procedures.js
Refactoring the behavior definition block a bit by adding a `createProcedureDefinitionBlock` method.
Probably easier to review with [whitespace ignored](https://github.com/code-dot-org/blockly/pull/107/files?w=1).
=> Function definition block creator

core/ui/block_space/block_space.js, core/ui/block_space/block_space_editor.js
Reverts code-dot-org/blockly#106
Breaks some code-dot-org tests https://circleci.com/gh/code-dot-org/code-dot-org/67745
=> Revert "Cross-tab copy / paste"

core/ui/block_space/block_space.js, core/ui/block_space/block_space_editor.js
Failed UI tests because I didn't account for ctrl+x 😵.
=> Re-merge "Cross-tab copy / paste"

core/code_generation/generator.js, generators/javascript.js
Follow-up to PR https://github.com/code-dot-org/blockly/pull/101.  Sample code generation:
```js
for (var count = 0; count < 10; count++) {
/* Unknown block: draw_turn_by_constant_dropdown */
}
```
=> Gracefully handle code generation for unknown blocks

blocks/procedures.js, core/ui/block.js
Fixes https://github.com/code-dot-org/blockly/issues/121.
=> Bump incompatible parameters when a function signature is modified

.drone.yml, .gitignore
Migrate this repository's Continuous Integration service from CircleCI to self-hosted Drone: https://codedotorg.atlassian.net/browse/INF-95
=> Add support for Continuous Integration Builds in Drone

core/ui/fields/field_rectangular_dropdown.js
https://codedotorg.atlassian.net/browse/STAR-50
=> Bugfix: STAR-50 Per-level Custom Animation JSON doesn't carry-over when remixing to a project, breaks blocks and tool box

core/ui/contract_editor/contract_editor.js, core/ui/function_editor.js
Partially to prevent script injection via translations, partially just because using innerHTML to build dom elements is not great.
I'm super open to feedback on how this can be made more readable!
=> Replace innerHTML with goog.dom.createDom for node creation

core/ui/function_editor.js
Accidentally removed in https://github.com/code-dot-org/blockly/pull/187/files#diff-15517595cdb4da6c8357781223e5a4daL958
=> Re-add some missing whitespace to the function editor

blocks/loops.js, msg/js/en_us.js
Description:
This is follow up work to update "controls_for" loop block in loops.js.
[jira](https://codedotorg.atlassian.net/secure/RapidBoard.jspa?rapidView=28&projectKey=FND&modal=detail&selectedIssue=FND-119)
Testing
Changes were tested on this level:  courseF_bee_for_challenge2_2019.level
=> Combine strings and variables: update function to use modified interpolateMsg function

i18n/codeorg-json-to-js.pl, i18n/codeorg-messages.sh
Specifically:
- Allow it to continue even if it encounters a locale without any translations
- Teach it to create the destination directories if they don't exist
[jira](https://codedotorg.atlassian.net/browse/FND-1090)
=> Make the i18n sync more resilient

.eslintrc.json, blocks/loops.js, core/ui/block.js, core/ui/block_space/block_space.js, core/ui/block_space/flyout.js, core/ui/block_svg/block_svg.js, core/ui/fields/field_colour.js, core/ui/fields/field_rectangular_dropdown.js, package-lock.json, package.json, tests/block_space_test.js, tests/blocks_test.js, tests/fields_test.js, tests/generator_test.js, tests/playground_requires.js, tests/test_requires_and_utils.js
Right now the lint rule *only* looks for ES5 violations, I'm going to tackle adding more rules in future PRs. Also it doesn't run before you commit yet.
=> Add ESLint and fix ES5 violations

core/utils/xml.js
drone branch build is failing because it is missing some updates.
=> FND-22 update drone branch

core/ui/block_space/flyout.js
This PR is just to run drone for https://github.com/code-dot-org/blockly/pull/265
=> Drone for PR#265

core/utils/xml.js
This PR is just to run drone for https://github.com/code-dot-org/blockly/pull/262
=> Drone for PR#262

core/ui/css.js, core/ui/fields/field_dropdown.js
This PR is just to run drone for https://github.com/code-dot-org/blockly/pull/270
=> Drone for PR#270

package-lock.json, package.json
This reverts commit e509a6d03355961bc2a4b135cf8a5421472baf1d.
=> Revert "5.0.0"

core/ui/fields/field_parameter.js, core/ui/function_editor.js
Part of https://github.com/code-dot-org/blockly/pull/317 all the description and discussion from that PR is actual for this PR.
This PR created only because I forgot to push 1 small commit to initial PR.
=> [DES-260] Add isDangerCancel parameter where needed
