code-dot-org/blockly

- deploy.sh
Its presense for some reason breaks apps tests
> Remove "use strict" from blockly_compressed.js

- core/ui/block_space/toolbox.js
Blocklyh.Toolbox.TreeNode is extending the native [goog.ui.tree.TreeNode](https://github.com/google/closure-library/blob/master/closure/goog/ui/tree/treenode.js),
in part to override the functionality of the "expand" element to make it
simply an empty span. Unfortunately, the [implementation of the google
element](https://github.com/google/closure-library/blob/master/closure/goog/ui/tree/basenode.js#L927) updated with the latest version of closure library, and the
Blockly implementation was not updated to match. It now is.
Note that the following grep indiciates that two other elements also extend native closure elements: 
```bash
$ git grep "goog.inherits(Blockly[^,]*, goog.[^)]*)"
ui/block_space/toolbox.js:goog.inherits(Blockly.Toolbox.TreeControl, goog.ui.tree.TreeControl); …
```
> Fixes Blockly.Toolbox.TreeNode implementation

- core/ui/block_space/block_space_editor.js
A little backstory: webkit browsers have a [long-existing bug](https://bugs.chromium.org/p/chromium/issues/detail?id=230599) where
shapes with control points take those points into account when
calculating the BBox. We had some workarounds in place to detect and
handle this bug, but Chrome [recently fixed this
issue](https://chromium.googlesource.com/chromium/src.git/+/8f4c8e6d2f1260d68f387b37f078457e4153bbb4) _only for paths_. This means that a container with an offending path
will still return the bugged BBox.
Unfortunately, our test was checking just a path, while our actual code
was using a container with a path, resulting in our test failling to
detect the presence of the bug.
The simple solution is to update our test to more accurately reflect our
real-life use case.
> Fix extra whitespace in webkit

- core/ui/fields/angle_helper.js
- core/ui/fields/field_angle_dropdown.js
- core/ui/fields/field_angle_textinput.js
When the angle helper's angle is changed by an external field change,
smoothly animate the transition rather than jumping directly to the new
value.
> Animate Angle Helper

- core/ui/fields/angle_helper.js
Rather than treating all 360 degrees of the angle helper as being equal,
subtly nudge the students toward making turns in the 0-180 region by
reducing the opacity of the tickmarks on the other half.
> Highlight Angler Helper's "primary" half

- core/ui/block.js
- tests/blocks_test.js
In a situation in which a top-level block with two input statements has
two or more blocks in the first one and a block containing a dropdown in
the second one, the blocks in the first statement end up getting bumped
out of position.
This is because the dropdown, upon initialization, checks for nearby
connections and bumps them away. And because the parent block is not yet
initialized when the dropdown block is being initialized, it sees the
blocks in the other statement as being positioned right on top of them,
and so bumps them away.
Blocks with parents avoid this by being rendered before their children
get rendered, and top-level blocks with previous connections (ie, blocks
without parents that really should have parents) avoid this by making a
call to `setIsUnused` before initializing …
> Fix block bumping on initialization

- core/ui/block.js
- core/ui/fields/field_dropdown.js
FieldDropdown's `changeHandler` is currently only called when the dropdown's value is changed through UI interaction. I'm adding an option to call it when it's changed by a call to `setTitleValue` as well.
I'll be using this option to fix the "Text in “When Any <X>” block doesn’t get properly updated on refresh" bug.
> Optionally call changehandler in setTitleValue

- core/ui/block.js
- core/ui/block_space/flyout.js
Right now, dragging certain blocks in from the toolbox causes existing blocks at the top left of the workspace to get bumped out of position. This happens the moment you mousedown on the toolbox block, not when you place it somewhere (which is when neighbor bumping is supposed to happen).
This happens because `bumpNeighbours_` is called indirectly by `domToBlock` while the newly created block is still sitting at `0,0`. `bumpNeighbors_` normally terminates immediately during block dragging, but the onMouseDown handler doesn't have a chance to run until the block is initialized. Instead, I'm setting the dragMode before creating the block.
Immediately setting it to `DRAG_MODE_FREELY_DRAGGING` breaks stuff, because that makes onMouseDown attempt to terminate the preceding drag, using a bunch …
> Set dragmode before creating block to stop unnecessary neighbour bump

- core/ui/css.js
Some custom CSS was overriding styles for a certain class of dropdowns,
but not doing so in an RTL-aware way. It now is.
Before | After
--- | ---
Fixes (part of) [axos: 571](https://codeorg.axosoft.com/viewitem?id=571)
> Size RTL dropdowns appropriately

- core/ui/block_space/block_space.js
- core/ui/fields/field.js
- core/ui/fields/field_colour.js
- core/ui/fields/field_dropdown.js
- core/ui/fields/field_rectangular_dropdown.js
- core/ui/fields/field_textinput.js
- tests/blockly_test.html
- tests/fields_test.js
Most (all?) of our editable fields in blockly don't reposition
themselves when the blockspace scrolls. (You can see an example of this [here](https://studio.code.org/s/grade1/stage/12/puzzle/9)) This solution adds a scroll
event which they can listen to to update themselves.
TODO: apply this approach to all fields, not just the rectangular
dropdown.
> Reposition fields on scroll

- core/initialization/inject.js
- core/ui/block_space/block_space.js
So other blockspaces on the page can make sure all the "special"
initialization has been done before they let themselves be created
> Add 'mainBlockSpace created' event

- core/ui/block_space/block_space.js
Rather than expecting other components to listen on the
MAIN_BLOCK_SPACE_CREATED event and handle all the associated logic
themselves, we do it internally.
> Add 'onMainBlockSpaceCreated' helper

- blocks/logic.js
- core/initialization/inject.js
Following the pattern of `Blockly.disableParamEditing`.
> Add option to disable editing of the number of branches in an if/else block

- core/ui/fields/field_textinput.js
A recent refactor of blockly's WidgetDiv positioning implementation
broke textinputs in RTL mode by removing a variable declaration; this
simply restores it.
> Fix FieldTextInput in RTL

- core/ui/function_editor.js
Make the modal function editor frame respect the `metrics.absoluteTop`.  This is a prerequisite for dragging blocks out of the modal function editor to the main block space.
Before: (absoluteTop = 150)
After: (absoluteTop = 150)
> Modal function editor should respect view metrics

- core/ui/block_space/block_space.js
- core/ui/block_space/block_space_editor.js
- core/ui/block_space/flyout.js
- core/ui/bubble.js
- core/ui/mutator.js
Allow blocks to be dragged outside the extents of their block space SVG.  Also ensures that the block is always at the top of the z-index while dragging.
> Move blocks to a top-level SVG while dragging

- deploy.sh
- package.json
Allows easier debugging on New Relic.  Without source maps:
After adding the source map:
> Build source maps for blockly_compressed.js

- core/ui/fields/field_dropdown.js
I spent a few days trying to track down a repro for this New Relic error without any luck.  Blockly somehow gets into a bad state where a `FieldDropdown` no longer has a reference to it's `sourceBlock_`.  Later, [drag is terminated for the selected block](https://github.com/code-dot-org/blockly/blob/828d2b04e54e4d30953d6b8ae3160d6b61bad588/core/ui/block.js#L355) which triggers a `BLOCK_SPACE_SCROLLED` event.  This [triggers a call to `positionWidgetDiv`](https://github.com/code-dot-org/blockly/blob/0fe9723fc49be45206c09415985182b14072b28b/core/ui/fields/field_colour.js#L138) which throws when `getRootSVGElement_` attempts to access the source block's block space.
Without a repro I don't have high confidence that this defensive fix will address the actual issue, but I think it's worth a …
> Speculative fix for `this.sourceBlock_ is null`

- core/utils/utils.js
Fixes an exception in Firefox when creating feedback block space with zero height.
Stack trace:
```
TypeError: Argument 1 of SVGPoint.matrixTransform is not an object.
Blockly.convertCoordinates()
blockly.js:29563
Blockly.BlockSpaceEditor.prototype.setBlockSpaceMetricsNoScroll_()
blockly.js:25367
Blockly.BlockSpaceEditor.prototype.svgResize()
blockly.js:25176
Blockly.BlockSpaceEditor.prototype.createDom_()
blockly.js:25003
Blockly.BlockSpaceEditor()
blockly.js:24931
Blockly.BlockSpace.createReadOnlyBlockSpace()
blockly.js:6808
[979]/FeedbackBlocks.prototype.render()
code-studio-common.js:32881
[1243]/FeedbackUtils.prototype.displayFeedback()
code-studio-common.js:46795
[154]/StudioApp.prototype.displayFeedback()
code-studio-common.js:8147
displayFeedback()
maze.js:5729 …
```
> Firefox returns null for getScreenCTM if svg is hidden or has 0 height

- core/ui/block.js
Fixes multiple touch points bug on iOS while dragging a block.
Repro on iOS:
- Start dragging a block.
- Use a second finger to start panning the page.
- Release when neither finger is touching the dragged block.
https://rpm.newrelic.com/accounts/501463/browser/3787364/js_errors#id=497715591
> Unselecting a block should always terminate drag

- core/ui/fields/field.js
- core/ui/fields/field_dropdown.js
PR https://github.com/code-dot-org/blockly/pull/38 indeed got rid of the `Blockly.FieldDropdown` error, however we started seeing new errors for `Blockly.FieldTextInput`.  Rather than add the null check for each field check, instead add it to the scroll listener before `this.positionWidgetDiv()` is called.
> New speculative fix for `this.sourceBlock_ is null` on all field types

- core/ui/block_space/flyout.js
We've had a lingering NewRelic error; TypeError: Cannot read property 'updateScrollableSize' of null
Repros on https://studio.code.org/s/20-hour/stage/13/puzzle/10
1. Drag a new “do something” function into the workspace
2. Click on the “Functions” category, then click anywhere else
https://rpm.newrelic.com/accounts/501463/browser/3787364/js_errors#id=-1241966532&tab_index=1&instance_index=1
The problem here is that when we drag the "do something" function into the workspace, the flyout gets populated with a `procedures_callnoreturn` block for the function definition; but when we call dispose on that function it [also disposes the call](https://github.com/code-dot-org/blockly/blob/staging/blocks/procedures.js#L171-L179). However since the call is in the blockSpace, the blockSpace is …
> [WIP] fix 'Cannot read property 'updateScrollableSize' of null' error

- core/initialization/inject.js
- core/ui/block_space/flyout.js
- core/utils/procedures.js
As it currently stands, Blockly works some magic with Function categories. Specifically, when it detects that a category is supposed to be a Function category, it ignores any levelbuilder-specified XML for that category and instead populates it with three different function definition blocks; `noreturn`, `return`, and `ifreturn`. It also populates it with call blocks for any functions that have already been defined.
Unfortunately, there are situations in which we want to present students with a subset of those definition blocks (mostly situations in which we have not yet introduced the concept of returns and would like to only expose `noreturn`). We therefore would like a new Blockly option for disabling the autopopulation of function definitions and instead actually relying on the …
> Add disable autopopulate option

- core/ui/block_svg/block_svg.js
> add IE-specific logic for positioning the Block Limit indicator

- core/connections/connection.js
- core/ui/fields/field.js
- core/ui/input.js
- core/utils/block_field_helper.js
The concept here is that we want to be able to add the ability for certain inputs/connections to augment the fields being attached to them with certain helpers. Specifically, we want for Artist blocks with value inputs like this one
To still be able to show the Angle Helper:
This PR proposes a generic system to do that. When we define the inputs for the block, in addition to validation checks we can add a Field Helper like so:
```
blockly.Blocks.draw_turn = {
// Block for turning left or right.
helpUrl: '',
init: function () {
this.setHSV(184, 1.00, 0.74);
this.appendValueInput('VALUE')
.setCheck(blockly.BlockValueType.NUMBER)
.addFieldHelper(blockly.BlockFieldHelper.ANGLE_HELPER, {
block: this,
directionTitle: 'DIR',
})
...
```
And then Fields can consult `getFieldHelperOptions_ ` from …
> add 'field helper' concept to connections

- core/ui/fields/field_angle_textinput.js
- core/ui/fields/field_textinput.js
- tests/test_dependency_map.js
Teach the existing FieldTextInput ow to leverage the new Field Helpers to display an Angle Helper when enabled.
This mostly involves moving a bunch of functionality from the child class FieldAngleTextInput into its parent; the child is now simply a version of FieldTextInput for which the angle helper is always enabled, rather than conditionally.
> Add angle helper to value inputs

- core/ui/block.js
- core/utils/xml.js
An already-existing property that was formerly just used for example blocks in the contract editor, we can now in the right-click menu lock a block to its parent, preventing the user from separating them (or from adding new blocks in between).
This can, among other things, be used to create user-visible function definitions that are movable but otherwise unchangeable by the user.
> Expose block "canDisconnectFromParent" property

- build-output/blockly_uncompressed.js
- core/code_generation/generator.js
- core/ui/block_space/block_space.js
- core/ui/block_space/block_space_editor.js
This fixes the workspace size issue that was still present on mobile safari on minecraft levels.
Handlers for DOM events are only set up for the first blockspace that gets created. Usually, the main workspace is that blockspace and everything is fine, but that changes when initialization blocks are present. The `xmlToBlocks` method creates a temporary blockspace, which steals the event handlers, and breaks resizing.
There's actually nothing specific to mobile safari about this, and it's almost completely unrelated to the very similar-looking bug I fixed last week in https://github.com/code-dot-org/code-dot-org/pull/18937. This bug is present for all browsers, for any level with initialization blocks, it's just way more noticeable on mobile safari because it automatically resizes right …
> Don't bind dom events on temporary blockspaces

- core/ui/function_editor.js
> Add .no-mc class to fix modal function editor button in MC

- circle.yml
- package.json
Specifically, those same versions used by the main @code-dot-org repo.
The specific motivation to do so is that the phantomjs-prebuilt is
failing on the (really quite old) version of node that we're currently
using. See https://circleci.com/gh/code-dot-org/blockly/253
> Update Circle config and package.json to more-recent versions of node

- core/connections/connection.js
I'm working on changing the tab shape for sprite blocks, here's some tangentially related cleanup.
This code draws the connection highlight that appears when you drag a block close to a connection on another block, either the previous/next connection or an input/output connection.
I'm reusing the existing `TAB_PATH_DOWN` constant instead of duplicating the svg path for the input/output highlight. I'm also applying an svg transform to flip it for RTL mode, which is how that's handled for most other block svg stuff.
> Use a transform to get RTL highlight from LTR path

- core/ui/block_space/block_space_editor.js
Followup to https://github.com/code-dot-org/blockly/pull/7
Chrome has since fixed https://bugs.chromium.org/p/chromium/issues/detail?id=230599, but our bug-detector is giving us false positives. The current test path actually does extend into negative-y terroritory, so chrome correctly reports it as having a height greater than 50: 
The triangle has a height and width of 50, the little notch at the top left is the bezier curve you get by going from (0,0) to (0,0) with both control points at (0, -5)
I'm replacing it with a curve that extends from (0, 50) to (125, 0), with the first control point at (75, -25). This catches older versions of chrome that include the control point, and thus report the height as 75px, but not newer ones that correctly determine that the curve stays on the sunny …
> Use a curve that's actually 50px tall to check for bbox bug

- core/ui/block_space/flyout.js
Fixes https://codeorg.zendesk.com/agent/tickets/137867.
Unfortunately we don't have any existing test coverage for `flyout.js`.  I'll get this tracked on the tech debt backlog.
> Only count used blocks towards the toolbox block limits

- blocks/functional_parameters.js
Some functional blocks have a "header" section with a dividing line underneath, e.g the `+` block below, and this was needlessly added to the `functional_parameters_get` block. Despite the fact that it's not even visible (it's outside the block's `clip-path`), the line is messing up the height calculation and creating an ugly gap in the input slot.
> Remove header divider line from functional param get block

- tests/playground.html
`goog.tweak` provides a more fully-featured way to set one or more flags in the query string. Until now you couldn't combine any of the other options with RTL mode because we only checked for the exact string `?rtl`.
> Use goog.tweak to manage RTL mode in blockly playground

- tests/block_space_test.js
- tests/blocks_test.js
- tests/hidden_blocks_test.js
- tests/test_requires_and_utils.js
- tests/unused_blocks_test.js
Turns out there's a nice test report when you load `blockly/tests/blockly_test.html` to run our unit tests in a browser. I've never seen it before because it got pushed way off the bottom of the page by all the `div`s left lying around by our unit tests.
> Clean up the dom after every test

- blocks/functional_procedures.js
- blocks/loops.js
- blocks/math.js
- blocks/procedures.js
- blocks/text.js
- blocks/variables.js
- core/ui/block_space/flyout.js
- core/ui/fields/field_variable.js
- core/utils/block_value_type.js
- core/utils/variables.js
- tests/blockly_test.html
- tests/generators/unittest.js
- tests/playground_requires.js
- tests/variables_test.js
In the process of creating the behavior editor, I've come across the need to create a toolbox category that autopopulates with a separate category of variable getter blocks (in particular for behaviors. but this is also useful for sprite and location variables). This PR enables that.
Basically, this PR modifies every blocks' `getVars` method to return a map of variables by category (usually there's just one category per block), so that the flyout creation code can find all the variables of a given category. All existing variables are now in the "Default" category, and https://github.com/code-dot-org/code-dot-org/pull/22233 puts the sprite variable getter/setter blocks into the "Sprite" category.
> Add variable categories

- blocks/procedures.js
- blocks/variables.js
- core/ui/block_space/flyout.js
- core/ui/function_editor.js
- core/utils/variables.js
- tests/playground.html
- tests/playground_requires.js
Adds a few options to the function editor so that, with the right constructor arguments, it can be a behavior editor instead.
* `msgOverrides` a map a of strings to replace various UI strings, e.g. replacing "Function" with "Behavior"
* `definitionBlockType` which block type to use for function definitions. Defaults to `procedures_defnoreturn`
* `opt_parameterBlockTypes` a map of block value types to the corresponding parameter blocks
* `opt_disableParamEditing` disables param editing for just this function editor, rather than globally.
See https://github.com/code-dot-org/code-dot-org/pull/22307/files#diff-3c5e6748726d3411afe8256d6ac20a3eR463 for how I intend to use these new options.
> Make the function editor more flexible so that it can become a behavior editor

- core/ui/block_space/toolbox.js
- package.json
There's some special touch event handling code here that makes the toolbox more responsive than simply relying on simulated mouse events. Unfortunately chrome is giving us two touch events (so it closes the toolbox category immediately after you open it), so I'm adding a check to ignore duplicated touch events.
> Ignore duplicate touch events

- core/ui/block_svg/block_svg.js
Angled tabs were already correct (using `V` instead of relative `v`).
> Fix square and rounded tabs for tall blocks

- core/ui/block_svg/block_svg.js
Follow up to PR https://github.com/code-dot-org/blockly/pull/100.  Better definition for type hints where the hint is the same color as the block.
Before:
After:
> Type hints should be below the blocklyPathDark shadow

- blocks/colour.js
- blocks/lists.js
- blocks/logic.js
- blocks/math.js
- blocks/text.js
- core/connections/connection.js
- core/ui/block.js
- core/ui/block_svg/block_svg.js
- tests/playground.html
- tests/playground_requires.js
One thing I found during this process:
The only place we use multiple type checks (vs. None or exactly 1 type) is for the the `text_length` / `list_length` and `text_empty` / `list_empty` blocks.  https://github.com/code-dot-org/blockly/blob/261ac3f64b7d5f0bb3303c6104d0e954009c2f34/blocks/lists.js#L179
Since they're separate blocks, we could collapse them to only take the corresponding type.  I think it's just an ease-of-use feature to allow them to be used interchangeably on strings and lists.
> Use output type to set default block color, when no color is specified

- core/ui/block_space/block_space_editor.js
Don't swallow non-Blockly cut/copy events.
> Only override clipboard events when a block is selected

- blocks/procedures.js
- core/ui/block_svg/block_svg.js
- msg/js/en_us.js
- tests/blocks_test.js
I extracted this isolated feature from PR https://github.com/code-dot-org/blockly/pull/118.  Allow any procedure to have optional type information (and strict checks) for its parameters.
The "type" dropdown is only provided when `Blockly.typeHints` are enabled.
> Parameter type mutation

- core/ui/block.js
Trying out an idea from https://docs.google.com/document/d/1wJMKXJS6Z8tsYQRRq93r7k4TTzG4jQbIXfKdKcSTZTI/edit
> When pressing ctrl/cmd, only drag a single block (not the full stack)

- core/utils/xml.js
In almost every case we want the block default for "inline", not what the user has saved in the Level Sources table.
> Stop reading & serializing `inline` attribute for block inputs

- core/ui/block_space/flyout.js
The normal dispose path for blocks in a flyout is here:
https://github.com/code-dot-org/blockly/blob/c93d76cb2c14399bf8929291a0f491fb967917a8/core/ui/block_space/flyout.js#L760-L773
However there is a second unintended path for call blocks, which causes them to be disposed twice:
https://github.com/code-dot-org/blockly/blob/c93d76cb2c14399bf8929291a0f491fb967917a8/core/ui/block_space/flyout.js#L377-L382
Here `opt_saveBlock` is the call block we want to keep — so all is good.  Except: procedure definition blocks override `dispose` to also remove matching call blocks:
https://github.com/code-dot-org/blockly/blob/c93d76cb2c14399bf8929291a0f491fb967917a8/blocks/procedures.js#L196-L204
The fix is to pass `opt_keepCallers` as true, since we're going to handle destroying the block ourself later.
> Pass `opt_keepCallers` as true to avoid double-dispose of call blocks in flyout

- core/connections/connection.js
- core/ui/block.js
- tests/block_space_test.js
Until now, `bumpNeighbours_` has only looked at opposing connections.  This PR updates the definition of "neighbors" to include situations where two blocks have an overlapping connection of the _same_ type.
In this case, since neither connection is "superior", we add new logic to determine which to bump:
1. Prioritize bumping unconnected blocks over connected blocks. 
2. When both blocks are unconnected, prioritize bumping blocks lower on the screen.
> Disambiguate (bump) connections of the same type

- core/ui/block_space/block_space_editor.js
- tests/block_space_test.js
Re-throw other errors so they don't get lost.
> Only catch errors related to malformed XML when pasting

- core/ui/block.js
- core/ui/block_space/block_space.js
- core/ui/block_svg/block_svg.js
- core/ui/block_svg/block_svg_unused.js
This is a slightly different approach to fixing the issue in PR https://github.com/code-dot-org/blockly/pull/11, to unblock PR https://github.com/code-dot-org/blockly/pull/129.
By not rendering the block in `this.setIsUnused();` we're able to postpone rendering until the full stack of blocks is built up, which will avoid any potential unwanted bumps.
> Wait to render "unused block" DOM until it's needed

- core/ui/block.js
- core/ui/block_space/flyout.js
- core/ui/contract_editor/example_view.js
- core/utils/xml.js
Reduces the time to open the "Sprites" tab of the toolbox on /p/spritelab from ~500ms to ~200ms.
**Before:**
**After:**
Both graphs have a horizontal time scale of about ~570ms.
> Don't fire unnecessary window "resize" events

- core/module.js
I removed all the direct uses of goog.Timer, but we still use it indirectly in the contract editor through `goog.ui.MenuButton`. Rewriting the contract editor to no longer use that would be a lot more work than just correctly setting the `goog.Timer`'s `defaultTimerObject`.
> Fix goog.Timer

- core/initialization/inject.js
- tests/blockly_test.js
It doesn't make sense to enable this option if the toolbox has categories, and that invalid combination led to a confusing bug recently.
> Disable topLevelAutopopulate if toolbox has categories

- core/ui/block.js
- core/ui/block_space/block_space.js
- core/ui/block_space/block_space_editor.js
- webpack.config.js
This adds lock/unlock movement methods to the block space editor to support limited autorun in https://github.com/code-dot-org/code-dot-org/pull/24196.
> Add editor methods to lock/unlock block movement

- core/ui/block.js
- tests/block_space_test.js
There's a bug with limited autorun in which the blocks becoming permanently immovable if your code is saved while block movement was locked. That's because `block.isMovable()` is used to determine the 'movable' attribute for the block's xml, and that method returns false if movement is locked in the block space. The next time you load the puzzle, the blocks will be initialized with `movable="false"` and you won't be able to move any of your blocks again without restarting.
This PR moves the `isMovementLocked()` check outside of `block.isMovable()` to the mousedown handler.
> Fix movement locking bug

- generators/javascript/loops.js
For consistency, I'm updating this to match the error thrown for infinite loops here: https://github.com/code-dot-org/code-dot-org/blob/7e2fcc28fbb791f0dd594c8b6e6192bca6f9a277/apps/src/lib/tools/jsinterpreter/CustomMarshalingInterpreter.js#L11
> Update infinite loop error to an Error object

- core/ui/block_space/block_space_editor.js
This fixes the share link copying bug reported on https://studio.code.org/s/coursee-2018/stage/13/puzzle/10. (If you click run+finish and try to copy the share URL, it doesn't work)
The problem was that if a block is highlighted (e.g. because the program was just running, and we're in an app that highlights blocks as they run), the blockly code here intercepts the copy event and prevents you from copying anything but the selected block to the clipboard.
I tried to fix this by looking at the currently focused element and only copying the block if you were just touching the workspace, but for some reason the blockly workspace doesn't become the focused element when you interact with it (`document.activeElement` points to `document.body`) so this broke block copying.
My solution is to only …
> Don't intercept copy event if text is selected

- core/ui/fields/field_dropdown.js
- tests/fields_test.js
Re-use the provided display name for a given option, if available.
```xml
<xml>
<block type="Dancelab_changeMoveLR">
<title name="SPRITE">dancer1</title>
<title name="MOVE" config="MOVES.DoubleJam,MOVES.Floss,MOVES.Clown">MOVES.Floss</title>
<title name="DIR">-1</title>
</block>
</xml>
```
Produces:
> FieldDropdown#setConfig should support non-numeric options

- core/utils/utils.js
```
> 'ontouchstart' in document.documentElement
false
```
(╯°□°）╯︵ ┻━┻
> Chrome 70 stopped including `ontouchstart` on elements

- core/ui/fields/field_variable.js
- core/utils/variables.js
- tests/variables_test.js
With guidance from @Bjvanminnen, alternate fix for PR https://github.com/code-dot-org/code-dot-org/pull/26085.
> Defend against empty variable names

- core/ui/fields/field_textinput.js
- tests/fields_test.js
Part of the solution for https://github.com/code-dot-org/dance-party/issues/321
Allows us to have a freeform text input in a block that can be constrained to accepting numeric input within a specified range.  The range can have a lower bound, and upper bound, or both.  The corresponding input element will be given the "number" type by default so the student cannot even type non-numeric characters into the field.  Invalid or blank input results in zero, unless zero is outside the given bounds in which case the zero is clamped to the nearest boundary.
> Add clampedNumberValidator for input fields

- core/ui/block.js
- tests/block_space_test.js
Will fix https://github.com/code-dot-org/dance-party/issues/62
There's a subtle case we're guarding against here and probably a deeper fix would be good, but as far as I can tell this does solve the case we care about.
An unconnected block (after paste) could bump a large section of connected blocks, which seems like behavior we never want to use. Now we use the new rules checking whether blocks are connected before bumping first, which gives nicer behavior.
Worse, in a few cases this could lead to an infinite loop of block-bumping:
I managed to write a unit test that reproduces this behavior with stock blocks, and after this fix it no longer does:
The infinite loop potential was introduced in https://github.com/code-dot-org/blockly/pull/128 so I checked to make sure I'm preserving the …
> Check block connectivity rules before superiority

- core/ui/fields/field_dropdown.js
[Years ago](https://github.com/code-dot-org/code-dot-org/pull/1542) I set the `max-height` of a blockly dropdown to be `250px` so that we would get a "peek" at the next option, if there were one, so that users would know it was scrollable on systems that don't have scrollbars.
Over time, this size seems to no longer show a peek, and so here's a change to bump it to `265px`:
This change has broad impact, so we should consider its adoption carefully.
This fixes https://github.com/code-dot-org/dance-party/issues/260.
> Increase the dropdown height to enable a "peek" at the next option again

- core/utils/utils.js
fixes (5) from https://github.com/code-dot-org/dance-party/issues/462 . applies to any finish dialog on blockly levels, including /s/dance, /s/artist, and many other HoC scripts.
> don't swallow backspace/delete on phone inputs

- core/ui/fields/field_image_dropdown.js
- core/ui/fields/field_rectangular_dropdown.js
Sprite costume tab uses image dropdown to popular the menu. As students are creating their own costumes, we want this dropdown to reflect the student's updates. Here, we update the blockly code that populates the options in those dropdowns (image dropdown extends rectangular dropdown), by allowing the array of choices, as previous used, or a function which will fetch the updated values.
> Rect dropdown and img dropdown allow function to update choices

- core/ui/block_space/flyout.js
Currently blocking curriculum team
For this task: https://codedotorg.atlassian.net/browse/STAR-289
This change allows for the behavior category in the toolbox to display both static blocks, like "{sprite} begins" and dynamic blocks, like "patrolling".
> Display static and dynamic blocks for behavior blocks

- core/ui/block.js
- tests/blocks_test.js
Part of our prototype for 'mini-toolboxes': https://docs.google.com/document/d/1VV9qHE0qjvas1o8-7zavDpkrbxG9gUmCFRas3Xlwtx4/edit#heading=h.8u7mwfss3758
This changes allows us to indicate a parent block, that when the current block is attached to, the current block will duplicate itself on drag and the duplicated block will continue the drag event (see gif above). 
Example of how it could be called from cdo repo:
> Duplicate block on drag from specified parent block

- core/ui/fields/field_image_dropdown.js
- core/ui/fields/field_rectangular_dropdown.js
- tests/fields_test.js
- tests/playground.html
- tests/playground_requires.js
Part of Sprite Costumes Feature: https://docs.google.com/document/d/1GBeHLqyTA0nHtD77LgpxIUAvB9xcGfMshb78Ucsn7jw/edit
We want to add a "Draw" and "More" button to the bottom of the costume picker. This PR extends the blockly dropdowns to accept an array of objects that specify the text and eventHandlers of buttons to be added to the bottom of the dropdown.
Example Image:
Playground block: (I didn't provide actual links to images, so please ignore the missing link icons and errors)
> Allow buttons in dropdowns

- karma.conf.js
- tests/blocks_test.js
- tests/test_requires_and_utils.js
Add `Blockly.Test.simulateDrag` and use it to verify that dragging a should-copy-on-drag block will duplicate it.
> Test helpers

- core/ui/contract_editor/contract_editor.js
- core/ui/contract_editor/example_view.js
- core/ui/contract_editor/x_button.js
Most of these uses of innerHTML are harmless, but a couple of them are using innerHTML to insert translated strings. (And arguably, the ones that _aren't_ using translated strings [probably _should_ be](https://codedotorg.atlassian.net/browse/FND-715)).
After this, there are only three instances of `innerHTML` assignment in this project:
```bash
$ git grep innerHTML
core/ui/contract_editor/contract_editor.js:  this.contractDiv_.innerHTML =
core/ui/function_editor.js:  this.container_.querySelector('#paramEditingArea').innerHTML =
core/ui/function_editor.js:  this.contractDiv_.innerHTML =
```
and all of them are actually being used to insert HTML. Followup work will involve making those safe.
> replace all uses of innerHTML assignment that are only intending to deal with text with textContent assignment

- core/ui/contract_editor/contract_editor.js
Accidentally removed in https://github.com/code-dot-org/blockly/pull/187/files#diff-07c4a25929b127db8ba45f84c9c05f7cL552
> Add some missing whitespace to the contract editor

- core/ui/fields/angle_helper.js
`e.offsetX/Y` was giving unpredictable values in Firefox, which was causing the flicker effect. According to https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX, it's an experimental feature anyways, so switching to always use `e.clientX/Y`, which seems more stable.
Also, moved the bounding rect to an instance variable to avoid repeating the expensive computation unnecessarily since the size of the dropdown does not ever change.
Before
After
[jira](https://codedotorg.atlassian.net/browse/STAR-650)
> Fix AngleHelper for Firefox

- core/ui/block_svg/block_svg.js
`getBBox` does not work with hidden elements in Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=528969
This is a targeted fix to fix https://studio.code.org/s/coursec-2019/stage/16/puzzle/6, but we should probably look into whether this is causing more widespread issues with Blockly labs on Firefox
> Fix block_svg for firefox

- core/ui/fields/field_angle_dropdown.js
Before:
After:
Longer dropdowns are unaffected:
> [Angle Picker] Adjust min height/width for small dropdowns

- core/ui/fields/angle_helper.js
- tests/angle_helper_test.js
Should be a no-op refactor. Mostly just changing names.
Also, we had a bunch of variables that were very closely related (circle_, circleR_, circleCenter_ as an example), and I thought it might be more clear if we grouped them in objects. So, the picker becomes an object that contains its vector, handle radius, svg elements, etc.
> Refactor Angle Helper and add tests

- core/ui/fields/field_rectangular_dropdown.js
We should fire a change event when you pick an option from a dropdown so that we update the preview immediately. Currently, we don't update the preview until you click outside the block.
Before:
After:
> Fire change event when new value is selected

- core/ui/fields/angle_helper.js
We started getting a ton of JS errors from somehow trying to call getAngle() when this.picker_ is null [See NewRelic](https://rpm.newrelic.com/accounts/501463/browser/3787364/errors/details#?tw_start=&tw_end=now&tw_offset=259200000&selectedItem=Cannot%20read%20property%20'angle'%20of%20null). We haven't been able to repro the issue ourselves, afaik.
Adding this preventative check in getAngle that handles the null case and defaults to 0 can't really hurt, though, and will silence the new relic noise.
> Catch case where this.picker_ is null

- core/ui/block_space/flyout.js
Currently for toolbox categories with a flyout button, there's an issue where the button overlaps the blocks as you scroll.
To resolve, we want to just add an opaque background behind the flyout button so that the blocks scroll underneath.
Before:
After:
> Add a background behind flyout button

- core/ui/block.js
- core/ui/fields/field_rectangular_dropdown.js
Pairs with https://github.com/code-dot-org/code-dot-org/pull/34975
This shadowing behavior is *not* general purpose, and will only work for the combination of blocks needed for mini toolboxes for events. That is, there is a clicked sprite pointer block that can shadow the sprite dropdown block in a clicked event block, and there are subject/object pointer blocks that can shadow the sprite dropdowns in a touch event block. If we ever need any other shadowing, that will need to be built separately.
> Sprite Lab Pointer Blocks Shadowing Functionality

- core/ui/block_space/block_space.js
- core/ui/block_space/block_space_editor.js
- core/ui/block_space/flyout.js
- tests/playground_requires.js
Prior to this change, the toolbox would expand to fully display all blocks. On small screens, long blocks would cause the toolbox to take up a disproportionate amount of space on the screen. In extreme cases, the toolbox would take up the entire screen and leave no space for the workspace. If we have toolbox categories, this isn't an issue because the toolbox is an overlay that can be dismissed. Without categories, however, this can cause certain labs to become unusable. We address this here by creating a clipping rectangle to define the maximum toolbox space.
- [Task](https://codedotorg.atlassian.net/browse/STAR-1104)
- [Bug](https://codedotorg.atlassian.net/browse/STAR-673)
Example where translation caused the toolbox to take up the entire screen: …
> Allowed the toolbox to display with a truncated width

- core/ui/block.js
This fixes the issue that caused this [revert](https://github.com/code-dot-org/code-dot-org/pull/35103), see also this [slack thread](https://codedotorg.slack.com/archives/C1B3PNDL7/p1591129863387900).
Basically the issue was that `newParent.getShadowBlocks()` is always true (`[]` is truthy), so we were rerendering the blockspace (which triggers a resize event) every time `setParent` was called. Updated to only call `this.blockSpace.render()` when blocks are added or removed from a parent with a mini flyout.
Before (Over 13000 resize events!):
After (204 resizes) (this is still a lot, but that's known/unrelated tech debt):
> Only rerender blockspace when shadow blocks change

- core/ui/block.js
https://github.com/code-dot-org/code-dot-org/pull/35215 implements the corresponding cdo changes.
When there's no sprite block to shadow, change the block text to "clicked/subject/object sprite" so it doesn't look weird.
Also contains a quick bug fix with the rerendering logic- we only need to rerender when a new block is added to an event stack, not all four cases.
> [Mini Toolbox] Dynamically update pointer blocks

- core/ui/block.js
We want to only update the preview once the block has been dropped, not while it's being dragged.
From Mike Harvey: "in most cases, i think students will be keeping the blocks under the same event but may be changing the sequence. if every change triggers a change back and forth, i’m worried it will feel like more is changing than actually is. it’d be impossible to leave a block in a being-dragged state, so it would still have to resolve one way or another depending on where the student put it."
I also have a small change to make the block stay the same height whether or not there's a thumbnail, along the same lines, to make it not seem like it's changing more than it is.
Before:
After:
> Don't update sprite pointer thumbnail until the drag has ended

- core/ui/block.js
- core/ui/block_space/flyout.js
- core/ui/fields/field_rectangular_dropdown.js
This sets up the blocks in the mini toolbox flyout to have the right sprite thumbnail.
Future work: Fix this rendering issue when there's no sprites in either socket
This only happens with the touch event block when there's no block in either socket. These all look fine:
> [MiniToolbox] Add thumbnails to blocks in the flyout

- core/ui/block.js
- core/ui/block_svg/block_svg.js
- tests/playground_requires.js
There was a rendering issue in some browsers (Firefox, IE, Edge):
The root cause is that `getComputedTextLength()` returns 0 if the text element is not visible. So basically, when we updated the object block, the "object" label thought its width was 0, so the preview went on top of it. The solution is to not update the minitoolbox blocks when the flyout is closed, and [this corresponding PR](https://github.com/code-dot-org/code-dot-org/pull/35455) updates them when the flyout opens
This PR also renames `tray` to `isMiniFlyoutOpen`
> Don't update shadow values on mini toolbox blocks when mini toolbox is closed

- core/ui/css.js
This makes block highlighting more obvious by making the fill of the block more yellow in addition to the existing yellow border. This highlight applies in all labs when a block is selected/clicked on and in some labs during run.
During run:
When selected:
- [jira](https://codedotorg.atlassian.net/browse/STAR-1151)
> Make block highlighting more obvious

- core/ui/block.js
two targeted fixes for IE compatibility. @jmkulwik tested and confirmed that mini toolbox now works in IE.
> IE fixes for minitoolbox

- core/ui/block_space/block_space_editor.js
- core/ui/block_space/flyout.js
- core/ui/css.js
Small fix to hidden flyout render properly in readOnly blockspaces (ie. _not_ render)
Also disallows dragging blocks out of the mini toolbox if it's readOnly
Before:
After:
> Render minitoolbox properly in embedded/readonly blockspaces

- package-lock.json
- package.json
To prevent re-introducing lint errors, run full linter on each commit. This doesn't just check changed files, but it's quite fast, so I think there's no harm in running over all files.
> Run lint on each commit

- .drone.yml
When the Drone server was rebuilt 2 months ago we lost the CodeCov.io API key being used by Blockly continuous integration builds to publish code coverage reports. Sign the Drone build script so that it is authenticated by the new Drone server and temporarily disable CodeCov.
> Temporarily disable CodeCov report and sign new Drone script

- blocks/procedures.js
- core/ui/block_space/block_space.js
- core/utils/procedures.js
- core/utils/xml.js
- generators/javascript/procedures.js
- tests/xml_test.js
Add an ID field to titles that persists across a roundtrip through XML
Before:
After:
This will be used for Sprite Lab shared behaviors so that we can generate functions by the id of the block, not the text on the block. This will enable us to translate the block text without changing the underlying function.
> Add support for IDs in block titles

- core/ui/function_editor.js
Follow up to https://github.com/code-dot-org/blockly/pull/254
This caused a regression for user-created behaviors. [slack thread](https://codedotorg.slack.com/archives/C946FMBGT/p1607385128161900)
Repro Steps:
1. Create a behavior (click create a behavior, change the name, add some blocks to the definition)
2. Use the behavior in your program
3. Click "Create a Behavior" again
Observe that your first behavior definition is still there (it shouldn't be)
4. Change the name and definition and click save
Observe that it changed the first behavior block too
And now your first behavior is totally gone.
The reason for this is that the first behavior gets id `do something`. Then you change the name (in this case to `my func`), which changes the value on the block, but not the id. Then when you …
> Keep id and name in sync for user created behaviors

- core/ui/function_editor.js
- core/utils/procedures.js
[Bug report](https://www.loom.com/share/f289f0c9292247ee941ca8ded4666282)
There were two small issues:
1. If you rename a shared behavior, we don't change the block id, just the text on the block. However, in the modal editor, we were showing the block id, so it didn't match the expected name. 
Before
After
2. When you rename a user-created behavior, we *do* change the id on the block definition block. However, we need to make sure we also change the associated id on all the existing caller blocks. This resulted in errors the next time you try to open the behavior definition. The fix in the blockly repo is to pass `userCreated` through to the changeHandler when the definition block is renamed. There will be a corresponding change …
> Fix behavior renaming

- core/ui/fields/field_image_dropdown.js
Unfortunately, I can't find any git history (just [Anybody can learn](https://github.com/code-dot-org/blockly/commit/26a17fd70dc273851d359bed0e24647e94e39eaa)) showing why we had originally wanted `xMidyMid slice`, but I don't think we want this anymore. In sprite lab it leads to suboptimal cropping of images in the sprite dropdown:
Before:
After:
I checked other places we use the FieldImageDropdown, and it doesn't look like it regresses anything for other labs. I think this is because the rest of our images are already square, so there's no cropping needed.
> Don't crop images in field image dropdowns

- core/ui/block_space/flyout.js
FND-1377: https://codedotorg.atlassian.net/browse/FND-1377?atlOrigin=eyJpIjoiOTc2NzRjMjk1NDllNDIzZDkzZTU4NzA4MGY5ZmVhZTIiLCJwIjoiaiJ9
In RTL context, the content of the flyout was positioned out to the right of the container it should be in.
This is likely because that is where it sits while hidden. This is not an issue in LTR context because it doesn't need to know the width of the content before positioning each element. In RTL we do need to know the width of the content before it's actually in the DOM.
To fix the issue, if RTL - we calculate the width of the flyout content before setting the X and Y offset positions.
Before:
After:
> FND-1377 Flyout subject blocks outside display area in RTL

- core/utils/xml.js
FND-22: https://codedotorg.atlassian.net/browse/FND-22?atlOrigin=eyJpIjoiYjExMmNlZGQ0ZjI2NGExZThiNTNiYzQwZGYwZTRjY2QiLCJwIjoiaiJ9
Most blocks were being positioned correctly in RTL context, however, inline blocks found in the instructions pane were often slightly offset and clipping into the regular text. Some blocks are so offset they aren't even visible.
The viewWidth is used to calculate offset in a regular context, but for inline we must use the width of the block itself.
Before:
After:
> FND-22: added a condition for positioning inline blocks in RLT context

- core/ui/block_space/block_space.js
- core/ui/fields/field_rectangular_dropdown.js
Update preview field on rectangular dropdowns when custom event `ANIMATIONS_CHANGE` is fired. This event will be fired only from Sprite Lab, so it will not affect any of our other Blockly environments.
Corresponding code-dot-org PR: https://github.com/code-dot-org/code-dot-org/pull/39724
> Refresh previews on image dropdown when animations change

- core/ui/css.js
- core/ui/fields/field_dropdown.js
FND-1487: https://codedotorg.atlassian.net/browse/FND-1487?atlOrigin=eyJpIjoiYjhiNWEwNzU0MjE5NDI3OWFkYzQyY2M4ZGQyNDZjZDgiLCJwIjoiaiJ9
While dragging a block in RTL, text and other elements become misaligned. To fix this, the blocklyDragSpace must be explicitly set to _LTR_ so that the coordinate's in the main block space and the drag block space align.
BEFORE:
AFTER:
https://user-images.githubusercontent.com/9528376/112697318-48392100-8e55-11eb-9562-12196e1a4e35.mov
62fc.gif)
Dropdown menus on RTL blocks are incorrectly positioned. There was some RTL specific code here already, but it was not following the right assumptions about RTL positioning. Perhaps it used to work, but some other RTL change caused this.
BEFORE:
AFTER:
> FND 1487 Unexpected RTL Behavior

- .eslintignore
- core/ui/block_space/flyout.js
- core/utils/xml.js
- tests/xml_test.js
I'm not 100% sure how these slipped through since `lint` is supposed to be in the pre-commit.
Fixing the errors and confirmed that the precommit is running correctly for me locally:
> Fix lint errors

- core/ui/fields/field_rectangular_dropdown.js
Buttons in the sprite dropdown menu are treated the same as the sprite images (they're all just `MenuItem`s)
This could lead to some awkward looking placement depending on the number of sprites:
Before
My solution here is to add empty, unselectable menu items to fill out the row in order to force the buttons to start on a new line:
After
This was the cleanest approach I could come up with, but if there's a better way, please lmk!
> [Sprite Lab] Force buttons in rectangular dropdown to a new row

- core/ui/block.js
When we add a new sprite block to the event socket, we need to update the thumbnails on any pointer blocks in the event stack. Previously, we accomplished this by re-rendering the whole blockspace, which does work, but is a lot of extra work and was a performance issue. Instead, we should just be re-rendering the event block (which also re-renders its children)
Thumbnails still update as expected:
> [Mini toolbox] Only re-render the event stack, not the whole blockspace

- core/ui/block_space/block_space.js
Small performance improvement to only render visible blocks. This should not result in any user-visible changes since invisible blocks shouldn't be visible anyways.
There will be a corresponding change in the code-dot-org repo to make sure spritelab behavior definition blocks are marked as not user visible, so we don't have to render them.
> Only render visible blocks

- core/utils/xml.js
- tests/block_space_test.js
- tests/xml_test.js
This change in the fork will facilitate migration to Google Blockly. Google Blockly renamed `<title>` to `<field>` in 2013. Currently, we have an override in our Google Blockly wrapper layer to make sure we still serialize XML using `<title>` tags [here](https://github.com/code-dot-org/code-dot-org/blob/staging-next/apps/src/blockly/addons/cdoXml.js#L30)
Instead, we should change our fork to match Google Blockly's behavior. With this change, Cdo Blockly will serialize XML using `<field>` tags, and then we can remove the override of `fieldToDom_` to that Google Blockly also serializes using `<field>` tags. Both versions of Blockly will still be able to deserialize XML that uses `<title>` tags, which is important for backwards compatibility.
Before
After
Import from XML still works with …
> Serialize to <field> and deserialize from <field>

- core/utils/xml.js
Requires the change in https://github.com/code-dot-org/code-dot-org/pull/44153
Before (mini toolbox is always closed on initial page load)
After (mini toolbox starts open if it was open when you saved)
> Serialize mini-toolbox state

- core/ui/block_space/flyout.js
Our site's top JS error is currently this:
```
Uncaught TypeError: Cannot read properties of null (reading 'contentHeight')
at Blockly.Flyout.setMetrics_
at blockly.js
at Blockly.BlockSpace.setMetrics
at Blockly.ScrollbarSvg.onScroll_ 
at Blockly.ScrollbarSvg.onMouseMoveKnob_ 
```
After acquiring a mouse this afternoon, the repro turned out to be this:
- open a flyout
- hover over scroll bar 
- hold down left mouse button to adjust scroll bar
- move mouse to the right of the flyout
- hold down right mouse button and flyout dismisses
- while both mouse buttons are still held down, move the mouse up and down
- the exception fires each time the mouse is moved
The fix is simple, and doesn't go too deep, but since `getMetrics_` explicitly …
> Fix flyout scrolling exception

- core/ui/function_editor.js
Before:
After:
- jira ticket: [SL-207](https://codedotorg.atlassian.net/browse/SL-207?atlOrigin=eyJpIjoiMTY3NWQ0ZDI5OTllNDVhYmI5NjAxMzI3MzJhMzFlZDUiLCJwIjoiaiJ9)
> [Student Learning] [SL-207] Fix Custom behavior dialog's green background being misplaced

- core/ui/function_editor.js
Addresses this eyes diff:
In the above case, we couldn't use `getToolboxWidth()`, because it turns out that it's calculated while the Variables flyout is still open. However, the new logic we were using to set the padding for levels without a toolbox actually works just fine even when we do have one!
Fix history:
* https://github.com/code-dot-org/blockly/pull/311
* https://github.com/code-dot-org/blockly/pull/314
The most recent attempt to fix the function editor frame introduced yet another new regression - this time in CSinAlg, which I didn't think to test manually. As a result, I reverted a Blockly bump in our cdo repo. Once this fix is merged, I will publish a new patch version and bump to that instead.
> Simplify logic for function editor frame

- core/ui/function_editor.js
Adds support to the function editor for new `behaviorPicker` blocks in Sprite Lab. This will only be merged if the following is approved:
- https://github.com/code-dot-org/code-dot-org/pull/50702
Once this is merged, a new release will need to be created. A bump in the code-dot-org repo should accompany the above PR.
> add support for behaviorPicker blocks
